name: Build & Test

on:
  push:
    branches:
      - develop

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 🔄
        uses: actions/checkout@v4

      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore NuGet packages 📂
        run: dotnet restore
        working-directory: ./

      - name: Build 🧱
        run: dotnet build --configuration Release --no-restore
        working-directory: ./

      # xUnit doesn't have a nice way to exclude some testing assemblies, so execute each assembly separately for now.
      - name: Test 🧪
        run: dotnet test tests/Sanctuary.Core.Tests/Sanctuary.Core.Tests.csproj --configuration Release --logger GitHubActions --no-build
        working-directory: ./
        